<div class="bitbucket_settings_block" style="display:none;">

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Destination URL', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'baseUrl-bitbucket', 'http://mystaticsite.com', '', ''); ?>

    <p><em><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></em></p>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Personl Access Token', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'bbToken', 'Bitbucket Personal Access Token', '<a href="https://bitbucket.com/settings/tokens/new" target="_blank">How do I get this?</a>', 'password'); ?>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Account & Repository Name', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'bbRepo', 'Account / Repository Name', 'ie, leonstafford/wordpress-static-html-plugin'); ?>

    <p><em>Repository cannot be empty, just create any file via the Bitbucket UI if needed</em></p>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Branch', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'bbBranch', 'Branch', 'usually \'master\' or \'bb-pages\''); ?>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Subdirectory', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'bbPath', 'Path within repository', 'Usually the repository root (leave this blank) or the \'doc\' folder'); ?>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Test Bitbucket Settings', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <button id="bitbucket-test-button" type="button" class="wp2static-btn btm-sm">Test Bitbucket Settings</button>
  </div>
</section>

</div>
